### ISSUE TITLE
meta file for books builds with wrong $MWK expansion

### ISSUE THREAD

**Issue by evelynmitchell** [a3n/miki#3] opened 2017-03-20 19:03 UTC
TopicA.rst says
Private Wilhelm perform his famous scream. $MWK/Books/Wilhelm/meta.json
for a $MWK of 
<path>/MikiWiki/ExampleWiki

But it builds to 
<path>/MikiWiki/Books/Wilhelm/meta.json 
when it should be
<path>/MikiWiki/ExampleWiki/Books/Wilhelm/meta.json

**Comment by a3n** [comment] 2017-03-20 22:03
Not checked in yet, new make targets goodlinks and badlinks. badlinks finds evelynmitchell's bad link, and one other.

    $ mwk badlinks
    
    # All links found in files that DO NOT EXIST in WK
    /home/aaron/MyMiki/ExampleWiki/TopicA/topicA.html:352:/home/aaron/MyMiki/Books/Wilhelm/meta.json
    /home/aaron/MyMiki/ExampleWiki/TopicX/rstTopicX.html:346:/home/aaron/MyMiki/TopicX/rstTopicX.rst

**Comment by a3n** [comment] 2017-03-20 23:01
Fixed in d1ee3f5b428a0a7a407d2734bb4483ba3735278a

Thanks again. Please have a look.

**Comment by evelynmitchell** [comment] 2017-03-21 10:07
I tried the new version, but it isn't quite the fix I had expected.
Finding the bad links is helpful, but the issue is the expansion, which creates the bad links. The sourcefile points to the right place, so the fix isn't to change it.

**Comment by a3n** [comment] 2017-03-21 14:32
Actually, in your reporting message, my source file did point to the wrong place:

    $MWK/Books/Wilhelm/meta.json

Notice `ExampleWiki` is missing.

That file (and the other I found) has been updated in d1ee3f5, as

    $MWK/ExampleWiki/Books/Wilhelm/meta.json

Have you completely updated your clone (git pull), or downloaded the most recent zip, or did you just download the latest makefile?
Have you tried something like

    mwk clean html

When I now go to topicA.html, the link to the meta.json file goes to the right place.

There has been one additional commit since the fix commit, 1c3ee648d8bd458a6c2b63114ec12940e2b9c768, which fixes a loosely related issue.

From the latest commit:

    $ git diff --name-only HEAD HEAD~2
    ExampleWiki/TopicA/topicA.rst
    ExampleWiki/TopicX/mdTopicX.md
    ExampleWiki/TopicX/rstTopicX.rst
    README.rst
    makefile

Thanks for persevering on this.

**Comment by a3n** [comment] 2017-03-21 22:50
Update:
The goodlinks and badlinks targets don't _fix_ the issue, they just expose it.

While using these targets on my actual wiki (lots of files) I discovered that
the two targets don't handle escaped characters in links, and they're really slow.

Fixed that in a210b5d7541f58071eb05e7cf93bee6d09aa0c6d

    $ git diff --name-only HEAD HEAD~3
    ExampleWiki/TopicA/topicA.rst
    ExampleWiki/TopicX/mdTopicX.md
    ExampleWiki/TopicX/rstTopicX.rst
    README.rst
    makefile

**Comment by a3n** [comment] 2017-03-21 23:08
Ah! I just finally noticed something from your original report.

Your $MWK points to <something>/ExampleWiki, rather than <something>.
Which is fine, except the links in ExampleWiki/* won't work.

The links in ExampleWiki/* assume that ExampleWiki is one below $MWK
(and not the actual location of $MWK), and so are written with ExampleWiki
in the links (except where I made a mistake).

I intended/assumed/vaguely thought that anyone who uses Miki
would eventually get rid of ExampleWiki, and their _real_ wiki files would be
at a level above ExampleWiki.

For my own daily use, and testing, I have two separate wikis.

My actual daily use wiki is MWK=~/MWK.

My test wiki is at MWK=~/MyWiki (and ExampleWiki is below that).

When I'm testing, I set MWK=~/MyWiki in the shell where I'm testing.

If you have your ExampleWiki mixed in with your real wiki, you could get rid of:

    ExampleWiki/UnnecessaryNavigationFile.rst
    ExampleWiki/TopicX/
    ExampleWiki/TopicA/

Clarified intent of ExampleWiki in 90e6f987585d814ddaef4e994eae03a54e8f4801

**Comment by a3n** [comment] 2017-03-23 02:48
Closing as "fixed" in 90e6f987585d814ddaef4e994eae03a54e8f4801

Issue was caused by unclear installation instructions in the README.
Examples were under a directory called `ExampleWiki`,
which led one to believe that setting the `MWK` environment variable to `ExampleWiki`,
_as the wiki_, was a workable arrangement.

My unclear expectation was that `ExampleWiki` would appear as a directory _under_ the directory pointed to by `$MWK`, and the links in `ExampleWiki's` source files were written with that assumption.

As part of the research into this report, I added a new make target, `badlinks`, which searches for bad links to internal wiki locations. This wasn't a fix, it just made sense to preserve that as a feature; it will be useful when a user moves/refactors internal wiki directories, and forgets to update links.

The actual fix was to rename `ExampleWiki` to `ExampleTopic`, make the README (hopefully) more clear on what `ExampleTopic` is and where it should be, and make the installation example commands more cut/pastable, in a way that will result in proper location of `ExampleTopic`.

Thanks again for the report, I look forward to any further reports.

**Closed by a3n** 2017-03-23 02:48 UTC
